.TH splc 1 2026-07-31 v0.0.0

.SH NAME
splc - a compiler for the Shakespeare Programming Language

.SH SYNOPSIS
.nf
\fBsplc\fR [\fB--\fR] source.spl
.fi

.SH DESCRIPTION
Basically, \fBsplc\fR reads a source file written in the SPL, processes it, and makes an output. Whether the output is \fI.splo\fR, the spl object file, or \fI.splasm\fR, the intermediate representation, depends on the command line argument.

.SH OPTIONS
.IP \fB-k\fR, \fB--kawaii\fR
Awakes the compiler chan. Specifically, the tone of the compiler output becomes cute.

.SH EXIT STATUS

.SH FILES

.SH BUGS

.SH AUTHOR
Developed by Doohyeon Won (logicseeker@naver.com)

.PP
For more information, please visit the GitHub repository:
\fIhttps://github.com/logic-finder/spl-toolset\fR

.PP
\fBsplc\fR is part of the \fBspl-toolset\fR suite.